<?php

declare(strict_types=1);

namespace Modules\Fixcity\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Modules\Fixcity\Enums\TicketPriorityEnum;
use Modules\Fixcity\Enums\TicketStatusEnum;
use Modules\Fixcity\Enums\TicketTypeEnum;
use Modules\Fixcity\Models\Ticket;
use Modules\Xot\Actions\Cast\SafeStringCastAction;
use Modules\Xot\Datas\XotData;

/**
 * Investor demo tickets — 50+ realistic segnalazioni across 8 Italian cities.
 *
 * Cities: Roma, Milano, Napoli, Torino, Firenze, Bologna, Genova, Venezia.
 * Categories: strade, illuminazione, rifiuti, verde pubblico, vandalismo, segnaletica, trasporti.
 * Statuses: open, in_progress, resolved, closed.
 * Timestamps: spread over last 30 days.
 * Priorities: low, medium, high, critical, urgent.
 *
 * Usage:
 *   php artisan db:seed --class="Modules\Fixcity\Database\Seeders\InvestoTicketSeeder"
 */
class InvestoTicketSeeder extends Seeder
{
    public function run(): void
    {
        $userClass = XotData::make()->getUserClass();
        $citizen = $userClass::query()->where('email', DemoUsersSeeder::CITIZEN_EMAIL)->first();
        $operator = $userClass::query()->where('email', DemoUsersSeeder::OPERATOR_EMAIL)->first();

        if ($citizen === null || $operator === null) {
            if ($this->command !== null) {
                $this->command->warn('InvestoTicketSeeder: demo users missing — run DemoUsersSeeder first.');
            }

            return;
        }

        $records = $this->ticketRecords();

        foreach ($records as $record) {
            $code = SafeStringCastAction::cast($record['code']);
            $name = SafeStringCastAction::cast($record['name']);
            $content = SafeStringCastAction::cast($record['content']);
            $lat = SafeStringCastAction::cast($record['lat']);
            $lng = SafeStringCastAction::cast($record['lng']);
            $address = SafeStringCastAction::cast($record['address']);
            $city = SafeStringCastAction::cast($record['city']);

            $location = [
                'lat' => $lat,
                'lng' => $lng,
                'latitude' => $lat,
                'longitude' => $lng,
                'address' => $address,
                'display_name' => $address.', '.$city.', Italia',
                'provider' => 'seed',
                'city' => $city,
                'country' => 'Italia',
                'country_code' => 'it',
            ];

            $createdDaysAgo = $record['days_ago'];
            $createdAt = Carbon::now()->subDays($createdDaysAgo)->subHours(random_int(0, 23))->subMinutes(random_int(0, 59));

            /** @var Ticket $ticket */
            $ticket = Ticket::query()->updateOrCreate(
                ['code' => $code],
                [
                    'name' => $name,
                    'content' => $content,
                    'owner_id' => $citizen->getKey(),
                    'responsible_id' => $operator->getKey(),
                    'status' => $record['status'],
                    'priority' => $record['priority'],
                    'type' => $record['type'],
                    'location' => $location,
                    'latitude' => $lat,
                    'longitude' => $lng,
                    'slug' => $record['slug'],
                    'created_by' => $citizen->getKey(),
                    'updated_by' => $operator->getKey(),
                ],
            );

            // Force timestamps for demo spread
            $ticket->forceFill([
                'created_at' => $createdAt,
                'updated_at' => $createdAt->copy()->addHours(random_int(1, 48)),
            ])->save();

            // Add citizen rating for resolved/closed tickets
            if (in_array($record['status'], [TicketStatusEnum::RESOLVED, TicketStatusEnum::CLOSED], true)) {
                $ticket->forceFill([
                    'citizen_rating' => random_int(3, 5),
                    'citizen_rated_at' => $createdAt->copy()->addDays(random_int(3, 10)),
                ])->save();
            }
        }

        if ($this->command !== null) {
            $this->command->info('InvestoTicketSeeder: '.count($records).' segnalazioni demo create.');
        }
    }

    /**
     * @return list<array{code: string, slug: string, name: string, content: string, status: TicketStatusEnum, priority: TicketPriorityEnum, type: TicketTypeEnum, lat: float, lng: float, address: string, city: string, days_ago: int}>
     */
    private function ticketRecords(): array
    {
        return [
            // ─── ROMA ───
            [
                'code' => 'INV-001',
                'slug' => 'roma-buca-via-del-corso',
                'name' => 'Buca profonda in Via del Corso',
                'content' => 'Avvallamento sul manto stradale davanti al civico 12, rischio per due ruote e pedoni. La buca si è approfondita nelle ultime 48 ore.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 41.9028,
                'lng' => 12.4964,
                'address' => 'Via del Corso 12, Roma',
                'city' => 'Roma',
                'days_ago' => 2,
            ],
            [
                'code' => 'INV-002',
                'slug' => 'roma-lampione-piazza-navona',
                'name' => 'Lampione spento Piazza Navona',
                'content' => 'Illuminazione pubblica non funzionante da oltre una settimana; area turistica poco illuminata di sera, potenziale rischio sicurezza.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::PUBLIC_LIGHTING,
                'lat' => 41.8992,
                'lng' => 12.4731,
                'address' => 'Piazza Navona, Roma',
                'city' => 'Roma',
                'days_ago' => 5,
            ],
            [
                'code' => 'INV-003',
                'slug' => 'roma-rifiuti-via-cavour',
                'name' => 'Cassonetti stracolmi Via Cavour',
                'content' => 'Contenitori per la raccolta differenziata non svuotati da 5 giorni; rifiuti abbandonati sul marciapiede, odori nauseabondi.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::WASTE_COLLECTION,
                'lat' => 41.8947,
                'lng' => 12.4989,
                'address' => 'Via Cavour 45, Roma',
                'city' => 'Roma',
                'days_ago' => 3,
            ],
            [
                'code' => 'INV-004',
                'slug' => 'roma-vandalismo-colosseo',
                'name' => 'Graffiti vandalici muro Colosseo',
                'content' => 'Nuovi graffiti apparsi sul muro perimetrale del Colosseo, area ad alto traffico turistico. Necessità pulitura urgente.',
                'status' => TicketStatusEnum::RESOLVED,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PUBLIC_BUILDINGS,
                'lat' => 41.8902,
                'lng' => 12.4922,
                'address' => 'Piazza del Colosseo, Roma',
                'city' => 'Roma',
                'days_ago' => 12,
            ],
            [
                'code' => 'INV-005',
                'slug' => 'roma-albero-via-appia',
                'name' => 'Albero pericolante Via Appia',
                'content' => 'Grande albero con tronco crepato; rischio caduta sui passanti e le auto in sosta. Intervento urgente richiesto.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::CRITICAL,
                'type' => TicketTypeEnum::PARKS_AND_GARDENS,
                'lat' => 41.8719,
                'lng' => 12.5113,
                'address' => 'Via Appia Antica 230, Roma',
                'city' => 'Roma',
                'days_ago' => 1,
            ],
            [
                'code' => 'INV-006',
                'slug' => 'roma-segnale-via-nazionale',
                'name' => 'Segnale di STOP abbattuto Via Nazionale',
                'content' => 'Il cartello di STOP all\'incrocio con Via delle Quattro Fontane è a terra dopo un incidente. Rischio incidenti.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::URGENT,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 41.8999,
                'lng' => 12.4956,
                'address' => 'Via Nazionale, Roma',
                'city' => 'Roma',
                'days_ago' => 1,
            ],
            [
                'code' => 'INV-007',
                'slug' => 'roma-pensilina-via-giovanni',
                'name' => 'Pensilina bus danneggiata Via G. Giolitti',
                'content' => 'Vetro rotto e struttura inclinata alla fermata del bus; pericolo per i pendolari in attesa.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::PUBLIC_TRANSPORT,
                'lat' => 41.8942,
                'lng' => 12.5056,
                'address' => 'Via Giovanni Giolitti, Roma',
                'city' => 'Roma',
                'days_ago' => 7,
            ],
            [
                'code' => 'INV-008',
                'slug' => 'roma-allagamento-via-ostiense',
                'name' => 'Allagamento Via Ostiense',
                'content' => 'Acqua stagnante dopo pioggia; tombino di scolo ostruito da detriti. Impossibilità di transito per le auto.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::SEWAGE_AND_DRAINAGE,
                'lat' => 41.8708,
                'lng' => 12.4817,
                'address' => 'Via Ostiense 100, Roma',
                'city' => 'Roma',
                'days_ago' => 15,
            ],
            [
                'code' => 'INV-009',
                'slug' => 'roma-marciapiede-via-tiburtina',
                'name' => 'Lastre marciapiede sollevate Via Tiburtina',
                'content' => 'Pericolo inciampo per pedoni; le radici degli alberi hanno sollevato il lastricato in diversi punti.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 41.8995,
                'lng' => 12.5278,
                'address' => 'Via Tiburtina, Roma',
                'city' => 'Roma',
                'days_ago' => 8,
            ],
            [
                'code' => 'INV-010',
                'slug' => 'roma-panchina-villa-borghese',
                'name' => 'Panchina rotta Villa Borghese',
                'content' => 'Panchina con schienale mancante e seduta instabile; area giochi adiacente frequentata da famiglie.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::LOW,
                'type' => TicketTypeEnum::URBAN_FURNITURE,
                'lat' => 41.9142,
                'lng' => 12.4923,
                'address' => 'Villa Borghese, Roma',
                'city' => 'Roma',
                'days_ago' => 20,
            ],

            // ─── MILANO ───
            [
                'code' => 'INV-011',
                'slug' => 'milano-buca-via-solferino',
                'name' => 'Buca in Via Solferino',
                'content' => 'Presenza di una buca pericolosa sul manto stradale che necessita intervento urgente. Profondità stimata 15cm.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 45.4781,
                'lng' => 9.1875,
                'address' => 'Via Solferino 24, Milano',
                'city' => 'Milano',
                'days_ago' => 3,
            ],
            [
                'code' => 'INV-012',
                'slug' => 'milano-panchina-parco-sempione',
                'name' => 'Panchina danneggiata Parco Sempione',
                'content' => 'La panchina risulta instabile e potenzialmente pericolosa per gli utenti del parco.',
                'status' => TicketStatusEnum::RESOLVED,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::URBAN_FURNITURE,
                'lat' => 45.4725,
                'lng' => 9.1779,
                'address' => 'Parco Sempione, Milano',
                'city' => 'Milano',
                'days_ago' => 18,
            ],
            [
                'code' => 'INV-013',
                'slug' => 'milano-lampione-via-dante',
                'name' => 'Lampione non funzionante Via Dante',
                'content' => 'Il lampione dell\'illuminazione pubblica è spento da diversi giorni; zona centrale ben frequentata.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::PUBLIC_LIGHTING,
                'lat' => 45.4647,
                'lng' => 9.1866,
                'address' => 'Via Dante 15, Milano',
                'city' => 'Milano',
                'days_ago' => 4,
            ],
            [
                'code' => 'INV-014',
                'slug' => 'milano-cestino-corso-buenos-aires',
                'name' => 'Cestino rifiuti stracolmo Corso Buenos Aires',
                'content' => 'Il cestino dei rifiuti non viene svuotato da giorni e sta creando problemi di igiene.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::WASTE_COLLECTION,
                'lat' => 45.4781,
                'lng' => 9.2107,
                'address' => 'Corso Buenos Aires 45, Milano',
                'city' => 'Milano',
                'days_ago' => 2,
            ],
            [
                'code' => 'INV-015',
                'slug' => 'milano-albero-viale-monza',
                'name' => 'Albero pericolante Viale Monza',
                'content' => 'Un albero sembra instabile e potrebbe cadere sul marciapiede trafficato.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::CRITICAL,
                'type' => TicketTypeEnum::PARKS_AND_GARDENS,
                'lat' => 45.4897,
                'lng' => 9.2175,
                'address' => 'Viale Monza 12, Milano',
                'city' => 'Milano',
                'days_ago' => 25,
            ],
            [
                'code' => 'INV-016',
                'slug' => 'milano-graffiti-stazione-centrale',
                'name' => 'Vandalismo muri Stazione Centrale',
                'content' => 'Graffiti sulle pareti esterne dello scalone della stazione; area ad alto traffico.',
                'status' => TicketStatusEnum::RESOLVED,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PUBLIC_BUILDINGS,
                'lat' => 45.4866,
                'lng' => 9.2033,
                'address' => 'Stazione Centrale, Milano',
                'city' => 'Milano',
                'days_ago' => 14,
            ],
            [
                'code' => 'INV-017',
                'slug' => 'milano-semaforo-via-liegi',
                'name' => 'Semaforo guasto Via Liegi',
                'content' => 'Semaforo fisso sul rosso da 3 giorni; caos nel traffico e rischio incidenti.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::URGENT,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 45.4765,
                'lng' => 9.2156,
                'address' => 'Via Liegi, Milano',
                'city' => 'Milano',
                'days_ago' => 1,
            ],
            [
                'code' => 'INV-018',
                'slug' => 'milano-metro-porta-genova',
                'name' => 'Ascensore metro guasto Porta Genova',
                'content' => 'Ascensore della stazione metro fuori servizio da una settimana; problema accessibilità.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PUBLIC_TRANSPORT,
                'lat' => 45.4535,
                'lng' => 9.1700,
                'address' => 'Porta Genova, Milano',
                'city' => 'Milano',
                'days_ago' => 6,
            ],
            [
                'code' => 'INV-019',
                'slug' => 'milano-marciapiede-via-montenapoleone',
                'name' => 'Marciapiede dissestato Via Montenapoleone',
                'content' => 'Lastricato danneggiato con buche e crepe; rischio inciampo per i passanti.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::LOW,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 45.4678,
                'lng' => 9.1956,
                'address' => 'Via Montenapoleone, Milano',
                'city' => 'Milano',
                'days_ago' => 9,
            ],
            [
                'code' => 'INV-020',
                'slug' => 'milano-rumore-cantiere-notturno',
                'name' => 'Rumore notturno cantiere Via Padova',
                'content' => 'Lavori in corso oltre l\'orario consentito (dopo le 22:00), disturbo della quiete pubblica dei residenti.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::ENVIRONMENTAL_REPORTS,
                'lat' => 45.4901,
                'lng' => 9.2234,
                'address' => 'Via Padova 100, Milano',
                'city' => 'Milano',
                'days_ago' => 5,
            ],

            // ─── NAPOLI ───
            [
                'code' => 'INV-021',
                'slug' => 'napoli-buga-via-toledo',
                'name' => 'Buca profonda Via Toledo',
                'content' => 'Grande avvallamento nel mezzo della strada, già due incidenti questa settimana.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::URGENT,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 40.8518,
                'lng' => 14.2681,
                'address' => 'Via Toledo 200, Napoli',
                'city' => 'Napoli',
                'days_ago' => 2,
            ],
            [
                'code' => 'INV-022',
                'slug' => 'napoli-illuminazione-via-nardones',
                'name' => 'Intera via al buio Via Nardones',
                'content' => 'Tutti i lampioni di Via Nardones sono spenti da due sere; zona residenziale con poca visibilità.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PUBLIC_LIGHTING,
                'lat' => 40.8523,
                'lng' => 14.2489,
                'address' => 'Via Nardones, Napoli',
                'city' => 'Napoli',
                'days_ago' => 3,
            ],
            [
                'code' => 'INV-023',
                'slug' => 'napoli-rifiuti-via-foria',
                'name' => 'Rifiuti abbandonati Via Foria',
                'content' => 'Elettrodomestici e mobili vecchi abbandonati sul ciglio della strada, oltre 10 giorni.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::ENVIRONMENTAL_REPORTS,
                'lat' => 40.8567,
                'lng' => 14.2534,
                'address' => 'Via Foria 50, Napoli',
                'city' => 'Napoli',
                'days_ago' => 7,
            ],
            [
                'code' => 'INV-024',
                'slug' => 'napoli-vandalismo-murales',
                'name' => 'Vandalismo murales Vomero',
                'content' => 'Murales deteriorato con vernice spray su tutta la facciata; opera di valore artistico.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::PUBLIC_BUILDINGS,
                'lat' => 40.8478,
                'lng' => 14.2389,
                'address' => 'Vomero, Napoli',
                'city' => 'Napoli',
                'days_ago' => 22,
            ],
            [
                'code' => 'INV-025',
                'slug' => 'napoli-albero-via-posillipo',
                'name' => 'Ramo pericoloso Via Posillipo',
                'content' => 'Albero con ramo spezzato a bassa altezza lungo la passeggiata; intervento potatura urgente.',
                'status' => TicketStatusEnum::RESOLVED,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PARKS_AND_GARDENS,
                'lat' => 40.8289,
                'lng' => 14.2012,
                'address' => 'Via Posillipo, Napoli',
                'city' => 'Napoli',
                'days_ago' => 16,
            ],
            [
                'code' => 'INV-026',
                'slug' => 'napoli-tombino-piazza-plebiscito',
                'name' => 'Tombino intasato Piazza del Plebiscito',
                'content' => 'Acqua stagnante dopo pioggia; tombino di scolo ostruito da detriti e foglie.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::SEWAGE_AND_DRAINAGE,
                'lat' => 40.8356,
                'lng' => 14.2489,
                'address' => 'Piazza del Plebiscito, Napoli',
                'city' => 'Napoli',
                'days_ago' => 4,
            ],
            [
                'code' => 'INV-027',
                'slug' => 'napoli-pensilina-via-nunzio',
                'name' => 'Pensilina bus danneggiata Via Nunzio',
                'content' => 'Struttura metallica arrugginita e vetro rotto alla fermata del bus; pericolo per i pendolari.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::LOW,
                'type' => TicketTypeEnum::PUBLIC_TRANSPORT,
                'lat' => 40.8445,
                'lng' => 14.2567,
                'address' => 'Via Nunzio, Napoli',
                'city' => 'Napoli',
                'days_ago' => 11,
            ],
            [
                'code' => 'INV-028',
                'slug' => 'napoli-fontana-via-partenope',
                'name' => 'Fontana pubblica disfunzionale Via Partenope',
                'content' => 'Fontana con acqua ferma e alghe; cattivo odore e rischio sanitario.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::URBAN_FURNITURE,
                'lat' => 40.8412,
                'lng' => 14.2467,
                'address' => 'Via Partenope, Napoli',
                'city' => 'Napoli',
                'days_ago' => 8,
            ],
            [
                'code' => 'INV-029',
                'slug' => 'napoli-barriera-via-nazionale',
                'name' => 'Guard-rail danneggiato Via Nazionale',
                'content' => 'Guard-rail piegato dopo incidente; protezione laterale mancante in curva pericolosa.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PUBLIC_SAFETY,
                'lat' => 40.8601,
                'lng' => 14.2601,
                'address' => 'Via Nazionale, Napoli',
                'city' => 'Napoli',
                'days_ago' => 5,
            ],
            [
                'code' => 'INV-030',
                'slug' => 'napoli-erba-alta-via-carlos',
                'name' => 'Erba alta e incuria Via Carlo III',
                'content' => 'Vegetazione alta oltre 1 metro che ostacola il passaggio dei pedoni.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::LOW,
                'type' => TicketTypeEnum::PARKS_AND_GARDENS,
                'lat' => 40.8534,
                'lng' => 14.2456,
                'address' => 'Via Carlo III, Napoli',
                'city' => 'Napoli',
                'days_ago' => 13,
            ],

            // ─── TORINO ───
            [
                'code' => 'INV-031',
                'slug' => 'torino-buga-via-garibaldi',
                'name' => 'Buca in Via Garibaldi',
                'content' => 'Buca con bordi affilati sul marciapiede; rischio caduta per i passanti.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 45.0703,
                'lng' => 7.6869,
                'address' => 'Via Garibaldi 30, Torino',
                'city' => 'Torino',
                'days_ago' => 6,
            ],
            [
                'code' => 'INV-032',
                'slug' => 'torino-lampione-via-roma',
                'name' => 'Lampione intermittente Via Roma',
                'content' => 'Lampione che lampeggia e si spegnene; crea condizioni di scarsa visibilità.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::PUBLIC_LIGHTING,
                'lat' => 45.0678,
                'lng' => 7.6834,
                'address' => 'Via Roma 100, Torino',
                'city' => 'Torino',
                'days_ago' => 4,
            ],
            [
                'code' => 'INV-033',
                'slug' => 'torino-rifiuti-via-po',
                'name' => 'Cassonetti pieni Via Po',
                'content' => 'Rifiuti oltre i cestini per 3 giorni; accumulo di cartoni e sacchetti.',
                'status' => TicketStatusEnum::RESOLVED,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::WASTE_COLLECTION,
                'lat' => 45.0656,
                'lng' => 7.6801,
                'address' => 'Via Po, Torino',
                'city' => 'Torino',
                'days_ago' => 17,
            ],
            [
                'code' => 'INV-034',
                'slug' => 'torino-vandalismo-mole',
                'name' => 'Vandalismo area Mole Antonelliana',
                'content' => 'Graffiti sulle mura perimetrali e rottami di vetro dopo notte di vandalismo.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PUBLIC_BUILDINGS,
                'lat' => 45.0678,
                'lng' => 7.6989,
                'address' => 'Mole Antonelliana, Torino',
                'city' => 'Torino',
                'days_ago' => 28,
            ],
            [
                'code' => 'INV-035',
                'slug' => 'torino-panchina-parco-del-valentino',
                'name' => 'Panchina rotta Parco del Valentino',
                'content' => 'Panchina con seduta mancante; area giochi adiacente frequentata da famiglie.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::LOW,
                'type' => TicketTypeEnum::URBAN_FURNITURE,
                'lat' => 45.0567,
                'lng' => 7.6956,
                'address' => 'Parco del Valentino, Torino',
                'city' => 'Torino',
                'days_ago' => 19,
            ],
            [
                'code' => 'INV-036',
                'slug' => 'torino-semaforo-via-cavour',
                'name' => 'Semaforo guasto Via Cavour',
                'content' => 'Semaforo spento in pieno giorno; automobilisti confusi all\'incrocio.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::URGENT,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 45.0723,
                'lng' => 7.6801,
                'address' => 'Via Cavour, Torino',
                'city' => 'Torino',
                'days_ago' => 1,
            ],
            [
                'code' => 'INV-037',
                'slug' => 'torino-tram-via-po',
                'name' => 'Rotaia tram dissestata Via Po',
                'content' => 'Rotaia del tram fuori posto; i convogli rallentano pericolosamente.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::CRITICAL,
                'type' => TicketTypeEnum::PUBLIC_TRANSPORT,
                'lat' => 45.0689,
                'lng' => 7.6834,
                'address' => 'Via Po, Torino',
                'city' => 'Torino',
                'days_ago' => 3,
            ],
            [
                'code' => 'INV-038',
                'slug' => 'torino-allagamento-via-giulia',
                'name' => 'Allagamento Via Giulia',
                'content' => 'Acqua ristagna da 2 giorni dopo pioggia; scarico ostruito.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::SEWAGE_AND_DRAINAGE,
                'lat' => 45.0745,
                'lng' => 7.6889,
                'address' => 'Via Giulia, Torino',
                'city' => 'Torino',
                'days_ago' => 21,
            ],
            [
                'code' => 'INV-039',
                'slug' => 'torino-marciapiede-via-pietro-micca',
                'name' => 'Marciapiede dissestato Via Pietro Micca',
                'content' => 'Lastre sollevate e buche profonde; pericoloso per passeggini e passeggini.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 45.0634,
                'lng' => 7.6912,
                'address' => 'Via Pietro Micca, Torino',
                'city' => 'Torino',
                'days_ago' => 10,
            ],
            [
                'code' => 'INV-040',
                'slug' => 'torino-fontana-piazza-solferino',
                'name' => 'Fontana Piazza Solferino disfunzionale',
                'content' => 'Fontana spenta e piena di sporco; cattivo odore nell\'area.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::LOW,
                'type' => TicketTypeEnum::URBAN_FURNITURE,
                'lat' => 45.0756,
                'lng' => 7.6856,
                'address' => 'Piazza Solferino, Torino',
                'city' => 'Torino',
                'days_ago' => 24,
            ],

            // ─── FIRENZE ───
            [
                'code' => 'INV-041',
                'slug' => 'firenze-buga-via-dei-calzaiuoli',
                'name' => 'Buca in Via dei Calzaiuoli',
                'content' => 'Avvallamento sotto il lastrico; pedoni devono schivare la buca.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 43.7696,
                'lng' => 11.2558,
                'address' => 'Via dei Calzaiuoli, Firenze',
                'city' => 'Firenze',
                'days_ago' => 7,
            ],
            [
                'code' => 'INV-042',
                'slug' => 'firenze-lampione-piazza-signoria',
                'name' => 'Lampione spento Piazza della Signoria',
                'content' => 'Lampione principale spento; piazza storica poco illuminata di sera.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::PUBLIC_LIGHTING,
                'lat' => 43.7689,
                'lng' => 11.2534,
                'address' => 'Piazza della Signoria, Firenze',
                'city' => 'Firenze',
                'days_ago' => 5,
            ],
            [
                'code' => 'INV-043',
                'slug' => 'firenze-rifiuti-via-dei-neri',
                'name' => 'Rifiuti abbandonati Via de\' Neri',
                'content' => 'Sacchetti di rifiuti accumulati vicino ai cestini; odori forti nel centro storico.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::WASTE_COLLECTION,
                'lat' => 43.7712,
                'lng' => 11.2578,
                'address' => 'Via de\' Neri, Firenze',
                'city' => 'Firenze',
                'days_ago' => 3,
            ],
            [
                'code' => 'INV-044',
                'slug' => 'firenze-vandalismo-ponte-vecchio',
                'name' => 'Vandalismo Ponte Vecchio',
                'content' => 'Lucchetti rotti e graffiti sulle mura del Ponte Vecchio; danno al patrimonio storico.',
                'status' => TicketStatusEnum::RESOLVED,
                'priority' => TicketPriorityEnum::CRITICAL,
                'type' => TicketTypeEnum::PUBLIC_BUILDINGS,
                'lat' => 43.7678,
                'lng' => 11.2523,
                'address' => 'Ponte Vecchio, Firenze',
                'city' => 'Firenze',
                'days_ago' => 15,
            ],
            [
                'code' => 'INV-045',
                'slug' => 'firenze-albero-via-romana',
                'name' => 'Albero pericolante Via Romana',
                'content' => 'Albero con crepa nel tronco; rischio caduta sui passanti.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PARKS_AND_GARDENS,
                'lat' => 43.7789,
                'lng' => 11.2612,
                'address' => 'Via Romana, Firenze',
                'city' => 'Firenze',
                'days_ago' => 27,
            ],
            [
                'code' => 'INV-046',
                'slug' => 'firenze-segnale-via-dei-serragli',
                'name' => 'Segnale stradale illeggibile Via de\' Serragli',
                'content' => 'Cartello coperto da edicole e sporcizia; automobilisti non lo vedono.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 43.7734,
                'lng' => 11.2489,
                'address' => 'Via de\' Serragli, Firenze',
                'city' => 'Firenze',
                'days_ago' => 8,
            ],
            [
                'code' => 'INV-047',
                'slug' => 'firenze-bus-via-dello-stadio',
                'name' => 'Fermata bus danneggiata Via dello Stadio',
                'content' => 'Pensilina con tetto mancante e panchina rotta.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::LOW,
                'type' => TicketTypeEnum::PUBLIC_TRANSPORT,
                'lat' => 43.7823,
                'lng' => 11.2678,
                'address' => 'Via dello Stadio, Firenze',
                'city' => 'Firenze',
                'days_ago' => 12,
            ],
            [
                'code' => 'INV-048',
                'slug' => 'firenze-allagamento-via-santa-monica',
                'name' => 'Allagamento Via Santa Monica',
                'content' => 'Acqua stagnante dopo pioggia; scarico ostruito da detriti.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::SEWAGE_AND_DRAINAGE,
                'lat' => 43.7756,
                'lng' => 11.2456,
                'address' => 'Via Santa Monica, Firenze',
                'city' => 'Firenze',
                'days_ago' => 23,
            ],
            [
                'code' => 'INV-049',
                'slug' => 'firenze-marciapiede-via-ghibellina',
                'name' => 'Marciapiede dissestato Via Ghibellina',
                'content' => 'Lastre sconnesse e buche; pericoloso per i pedoni.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 43.7767,
                'lng' => 11.2501,
                'address' => 'Via Ghibellina, Firenze',
                'city' => 'Firenze',
                'days_ago' => 18,
            ],
            [
                'code' => 'INV-050',
                'slug' => 'firenze-fontana-piazza-croce',
                'name' => 'Fontana Piazza della Croce disfunzionale',
                'content' => 'Fontana con acqua ferma e alghe; cattivo odore.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::LOW,
                'type' => TicketTypeEnum::URBAN_FURNITURE,
                'lat' => 43.7723,
                'lng' => 11.2467,
                'address' => 'Piazza della Croce, Firenze',
                'city' => 'Firenze',
                'days_ago' => 26,
            ],

            // ─── BOLOGNA ───
            [
                'code' => 'INV-051',
                'slug' => 'bologna-buga-via-indipendenza',
                'name' => 'Buca in Via Indipendenza',
                'content' => 'Buca profonda nel centro storico; rischio per pedoni e ciclisti.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 44.4949,
                'lng' => 11.3426,
                'address' => 'Via Indipendenza, Bologna',
                'city' => 'Bologna',
                'days_ago' => 4,
            ],
            [
                'code' => 'INV-052',
                'slug' => 'bologna-lampione-piazza-maggiore',
                'name' => 'Lampione spento Piazza Maggiore',
                'content' => 'Lampione principale non funzionante; piazza poco illuminata.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::PUBLIC_LIGHTING,
                'lat' => 44.4938,
                'lng' => 11.3423,
                'address' => 'Piazza Maggiore, Bologna',
                'city' => 'Bologna',
                'days_ago' => 6,
            ],
            [
                'code' => 'INV-053',
                'slug' => 'bologna-rifiuti-via-rufillo',
                'name' => 'Rifiuti stracolmi Via Ruffillo',
                'content' => 'Cestini pieni e rifiuti abbandonati sul marciapiede.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::WASTE_COLLECTION,
                'lat' => 44.4878,
                'lng' => 11.3567,
                'address' => 'Via Ruffillo, Bologna',
                'city' => 'Bologna',
                'days_ago' => 3,
            ],
            [
                'code' => 'INV-054',
                'slug' => 'bologna-vandalismo-portico',
                'name' => 'Vandalismo sotto i Portici',
                'content' => 'Graffiti sui pilastri dei portici; danno al patrimonio UNESCO.',
                'status' => TicketStatusEnum::RESOLVED,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PUBLIC_BUILDINGS,
                'lat' => 44.4967,
                'lng' => 11.3445,
                'address' => 'Portico di Via Zamboni, Bologna',
                'city' => 'Bologna',
                'days_ago' => 20,
            ],
            [
                'code' => 'INV-055',
                'slug' => 'bologna-albero-via-mascarella',
                'name' => 'Albero pericolante Via Mascarella',
                'content' => 'Albero con ramo spezzato che pende sulla strada.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::CRITICAL,
                'type' => TicketTypeEnum::PARKS_AND_GARDENS,
                'lat' => 44.4901,
                'lng' => 11.3389,
                'address' => 'Via Mascarella, Bologna',
                'city' => 'Bologna',
                'days_ago' => 29,
            ],
            [
                'code' => 'INV-056',
                'slug' => 'bologna-semaforo-via-zamboni',
                'name' => 'Semaforo guasto Via Zamboni',
                'content' => 'Semaforo lampeggiante senza regolarità; confusione universitaria.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::URGENT,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 44.4956,
                'lng' => 11.3412,
                'address' => 'Via Zamboni, Bologna',
                'city' => 'Bologna',
                'days_ago' => 1,
            ],
            [
                'code' => 'INV-057',
                'slug' => 'bologna-tram-via-uzielli',
                'name' => 'Rotaia tram dissestata Via Uzielli',
                'content' => 'Rotaia fuori posto; convogli rallentano pericolosamente.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PUBLIC_TRANSPORT,
                'lat' => 44.4934,
                'lng' => 11.3501,
                'address' => 'Via Uzielli, Bologna',
                'city' => 'Bologna',
                'days_ago' => 5,
            ],
            [
                'code' => 'INV-058',
                'slug' => 'bologna-allagamento-via-murri',
                'name' => 'Allagamento Via Murri',
                'content' => 'Acqua ristagna da 3 giorni; scarico ostruito.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::SEWAGE_AND_DRAINAGE,
                'lat' => 44.4889,
                'lng' => 11.3367,
                'address' => 'Via Murri, Bologna',
                'city' => 'Bologna',
                'days_ago' => 16,
            ],
            [
                'code' => 'INV-059',
                'slug' => 'bologna-marciapiede-via-selmi',
                'name' => 'Marciapiede dissestato Via Selmi',
                'content' => 'Lastre sollevate e buche; pericoloso per i pedoni.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 44.4978,
                'lng' => 11.3456,
                'address' => 'Via Selmi, Bologna',
                'city' => 'Bologna',
                'days_ago' => 14,
            ],
            [
                'code' => 'INV-060',
                'slug' => 'bologna-panchina-parco-montagnola',
                'name' => 'Panchina rotta Parco Montagnola',
                'content' => 'Panchina con schienale mancante; area giochi frequentata.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::LOW,
                'type' => TicketTypeEnum::URBAN_FURNITURE,
                'lat' => 44.4912,
                'lng' => 11.3345,
                'address' => 'Parco Montagnola, Bologna',
                'city' => 'Bologna',
                'days_ago' => 25,
            ],

            // ─── GENOVA ───
            [
                'code' => 'INV-061',
                'slug' => 'genova-buga-via-san-lorenzo',
                'name' => 'Buca in Via San Lorenzo',
                'content' => 'Buca profonda nel centro storico; rischio per pedoni.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 44.4056,
                'lng' => 8.9463,
                'address' => 'Via San Lorenzo, Genova',
                'city' => 'Genova',
                'days_ago' => 5,
            ],
            [
                'code' => 'INV-062',
                'slug' => 'genova-lampione-via-balbi',
                'name' => 'Lampione spento Via Balbi',
                'content' => 'Lampione non funzionante; via poco illuminata di sera.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::PUBLIC_LIGHTING,
                'lat' => 44.4078,
                'lng' => 8.9489,
                'address' => 'Via Balbi, Genova',
                'city' => 'Genova',
                'days_ago' => 7,
            ],
            [
                'code' => 'INV-063',
                'slug' => 'genova-rifiuti-via-20-settembre',
                'name' => 'Rifiuti abbandonati Via XX Settembre',
                'content' => 'Mobili e rifiuti ingombranti abbandonati sul marciapiede.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::WASTE_COLLECTION,
                'lat' => 44.4101,
                'lng' => 8.9512,
                'address' => 'Via XX Settembre, Genova',
                'city' => 'Genova',
                'days_ago' => 4,
            ],
            [
                'code' => 'INV-064',
                'slug' => 'genova-vandalismo-porta-pila',
                'name' => 'Vandalismo Porta Pila',
                'content' => 'Graffiti sulle mura medievali; danno al patrimonio storico.',
                'status' => TicketStatusEnum::RESOLVED,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PUBLIC_BUILDINGS,
                'lat' => 44.4023,
                'lng' => 8.9345,
                'address' => 'Porta Pila, Genova',
                'city' => 'Genova',
                'days_ago' => 18,
            ],
            [
                'code' => 'INV-065',
                'slug' => 'genova-albero-via-assarotti',
                'name' => 'Albero pericolante Via Assarotti',
                'content' => 'Albero con tronco crepato; rischio caduta.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::CRITICAL,
                'type' => TicketTypeEnum::PARKS_AND_GARDENS,
                'lat' => 44.4134,
                'lng' => 8.9567,
                'address' => 'Via Assarotti, Genova',
                'city' => 'Genova',
                'days_ago' => 24,
            ],
            [
                'code' => 'INV-066',
                'slug' => 'genova-semaforo-via-poce',
                'name' => 'Semaforo guasto Via Po',
                'content' => 'Semaforo spento; automobilisti confusi.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::URGENT,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 44.4156,
                'lng' => 8.9601,
                'address' => 'Via Po, Genova',
                'city' => 'Genova',
                'days_ago' => 2,
            ],
            [
                'code' => 'INV-067',
                'slug' => 'genova-bus-via-dante',
                'name' => 'Fermata bus danneggiata Via Dante',
                'content' => 'Pensilina con vetro rotto e panchina instabile.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::LOW,
                'type' => TicketTypeEnum::PUBLIC_TRANSPORT,
                'lat' => 44.4089,
                'lng' => 8.9534,
                'address' => 'Via Dante, Genova',
                'city' => 'Genova',
                'days_ago' => 11,
            ],
            [
                'code' => 'INV-068',
                'slug' => 'genova-allagamento-via-sottoripa',
                'name' => 'Allagamento Via Sottoripa',
                'content' => 'Acqua stagnante dopo pioggia; scarico ostruito.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::SEWAGE_AND_DRAINAGE,
                'lat' => 44.4045,
                'lng' => 8.9423,
                'address' => 'Via Sottoripa, Genova',
                'city' => 'Genova',
                'days_ago' => 22,
            ],
            [
                'code' => 'INV-069',
                'slug' => 'genova-marciapiede-via-garibaldi',
                'name' => 'Marciapiede dissestato Via Garibaldi',
                'content' => 'Lastre sollevate e buche; pericoloso per i pedoni.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 44.4112,
                'lng' => 8.9556,
                'address' => 'Via Garibaldi, Genova',
                'city' => 'Genova',
                'days_ago' => 13,
            ],
            [
                'code' => 'INV-070',
                'slug' => 'genova-fontana-piazza-de-ferrari',
                'name' => 'Fontana Piazza De Ferrari disfunzionale',
                'content' => 'Fontana spenta e piena di sporco; cattivo odore.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::LOW,
                'type' => TicketTypeEnum::URBAN_FURNITURE,
                'lat' => 44.4067,
                'lng' => 8.9445,
                'address' => 'Piazza De Ferrari, Genova',
                'city' => 'Genova',
                'days_ago' => 27,
            ],

            // ─── VENEZIA ───
            [
                'code' => 'INV-071',
                'slug' => 'venezia-buga-via-garibaldi',
                'name' => 'Buca in Via Garibaldi',
                'content' => 'Buca profonda nel manto stradale; rischio per pedoni.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 45.4408,
                'lng' => 12.3155,
                'address' => 'Via Garibaldi, Venezia',
                'city' => 'Venezia',
                'days_ago' => 6,
            ],
            [
                'code' => 'INV-072',
                'slug' => 'venezia-lampione-rialto',
                'name' => 'Lampione spento Ponte di Rialto',
                'content' => 'Lampione non funzionante; area turistica poco illuminata.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::PUBLIC_LIGHTING,
                'lat' => 45.4389,
                'lng' => 12.3356,
                'address' => 'Ponte di Rialto, Venezia',
                'city' => 'Venezia',
                'days_ago' => 8,
            ],
            [
                'code' => 'INV-073',
                'slug' => 'venezia-rifiuti-via-giudecca',
                'name' => 'Rifiuti abbandonati Via Giudecca',
                'content' => 'Sacchetti di rifiuti accumulati vicino ai cestini.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::WASTE_COLLECTION,
                'lat' => 45.4345,
                'lng' => 12.3289,
                'address' => 'Via Giudecca, Venezia',
                'city' => 'Venezia',
                'days_ago' => 5,
            ],
            [
                'code' => 'INV-074',
                'slug' => 'venezia-vandalismo-palazzo-ducale',
                'name' => 'Vandalismo Palazzo Ducale',
                'content' => 'Graffiti sulle mura esterne; danno al patrimonio storico.',
                'status' => TicketStatusEnum::RESOLVED,
                'priority' => TicketPriorityEnum::CRITICAL,
                'type' => TicketTypeEnum::PUBLIC_BUILDINGS,
                'lat' => 45.4334,
                'lng' => 12.3401,
                'address' => 'Palazzo Ducale, Venezia',
                'city' => 'Venezia',
                'days_ago' => 19,
            ],
            [
                'code' => 'INV-075',
                'slug' => 'venezia-albero-via-santa-maria',
                'name' => 'Albero pericolante Via Santa Maria',
                'content' => 'Albero con ramo spezzato che pende sulla strada.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PARKS_AND_GARDENS,
                'lat' => 45.4378,
                'lng' => 12.3234,
                'address' => 'Via Santa Maria, Venezia',
                'city' => 'Venezia',
                'days_ago' => 26,
            ],
            [
                'code' => 'INV-076',
                'slug' => 'venezia-semaforo-via-marco-polo',
                'name' => 'Semaforo guasto Via Marco Polo',
                'content' => 'Semaforo spento; automobilisti confusi.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::URGENT,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 45.4456,
                'lng' => 12.3189,
                'address' => 'Via Marco Polo, Venezia',
                'city' => 'Venezia',
                'days_ago' => 1,
            ],
            [
                'code' => 'INV-077',
                'slug' => 'venezia-bacino-san-marco',
                'name' => 'Bacino San Marco danneggiato',
                'content' => 'Bancale dissestato nel Bacino San Marco; rischio per le imbarcazioni.',
                'status' => TicketStatusEnum::IN_PROGRESS,
                'priority' => TicketPriorityEnum::HIGH,
                'type' => TicketTypeEnum::PUBLIC_SAFETY,
                'lat' => 45.4323,
                'lng' => 12.3445,
                'address' => 'Bacino San Marco, Venezia',
                'city' => 'Venezia',
                'days_ago' => 9,
            ],
            [
                'code' => 'INV-078',
                'slug' => 'venezia-allagamento-rio-novo',
                'name' => 'Allagamento Rio Novo',
                'content' => 'Acqua ristagna dopo pioggia; scarico ostruito.',
                'status' => TicketStatusEnum::CLOSED,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::SEWAGE_AND_DRAINAGE,
                'lat' => 45.4367,
                'lng' => 12.3267,
                'address' => 'Rio Novo, Venezia',
                'city' => 'Venezia',
                'days_ago' => 21,
            ],
            [
                'code' => 'INV-079',
                'slug' => 'venezia-marciapiede-via-27-aprile',
                'name' => 'Marciapiede dissestato Via 27 Aprile',
                'content' => 'Lastre sollevate e buche; pericoloso per i pedoni.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::MEDIUM,
                'type' => TicketTypeEnum::ROAD_MAINTENANCE,
                'lat' => 45.4423,
                'lng' => 12.3212,
                'address' => 'Via 27 Aprile, Venezia',
                'city' => 'Venezia',
                'days_ago' => 15,
            ],
            [
                'code' => 'INV-080',
                'slug' => 'venezia-panchina-piazzale-roma',
                'name' => 'Panchina rotta Piazzale Roma',
                'content' => 'Panchina con seduta mancante; area di sosta frequentata.',
                'status' => TicketStatusEnum::OPEN,
                'priority' => TicketPriorityEnum::LOW,
                'type' => TicketTypeEnum::URBAN_FURNITURE,
                'lat' => 45.4389,
                'lng' => 12.3189,
                'address' => 'Piazzale Roma, Venezia',
                'city' => 'Venezia',
                'days_ago' => 30,
            ],
        ];
    }
}
