<?php

declare(strict_types=1);

namespace Modules\Fixcity\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Modules\User\Database\Factories\UserFactory;
use Modules\Xot\Datas\XotData;

/**
 * Investor demo users — cittadini, operatori e admin con nomi italiani realistici.
 *
 * Usage:
 *   php artisan db:seed --class="Modules\Fixcity\Database\Seeders\InvestoUsersSeeder"
 */
class InvestoUsersSeeder extends Seeder
{
    public function run(): void
    {
        $userClass = XotData::make()->getUserClass();

        foreach (self::users() as $demo) {
            $existing = $userClass::query()->where('email', $demo['email'])->first();
            $attributes = [
                'name' => $demo['first_name'].' '.$demo['last_name'],
                'first_name' => $demo['first_name'],
                'last_name' => $demo['last_name'],
                'email_verified_at' => now(),
                'password' => Hash::make($demo['password']),
                'lang' => 'it',
                'is_active' => true,
                'type' => $demo['type'],
                'state' => 'active',
                'is_otp' => false,
            ];

            if ($existing !== null) {
                $existing->fill($attributes)->save();

                continue;
            }

            UserFactory::new()->createOne([
                'email' => $demo['email'],
                ...$attributes,
            ]);
        }

        if ($this->command !== null) {
            $this->command->info('InvestoUsersSeeder: '.count(self::users()).' utenti demo creati.');
        }
    }

    /**
     * @return list<array{email: non-empty-string, first_name: non-empty-string, last_name: non-empty-string, type: non-empty-string, password: non-empty-string}>
     */
    private static function users(): array
    {
        return [
            [
                'email' => 'giulia.rossi@gmail.com',
                'first_name' => 'Giulia',
                'last_name' => 'Rossi',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'marco.bianchi@libero.it',
                'first_name' => 'Marco',
                'last_name' => 'Bianchi',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'sara.verdi@outlook.it',
                'first_name' => 'Sara',
                'last_name' => 'Verdi',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'luca.ferrari@yahoo.it',
                'first_name' => 'Luca',
                'last_name' => 'Ferrari',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'elena.romano@gmail.com',
                'first_name' => 'Elena',
                'last_name' => 'Romano',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'davide.esposito@libero.it',
                'first_name' => 'Davide',
                'last_name' => 'Esposito',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'chiara.colombo@outlook.it',
                'first_name' => 'Chiara',
                'last_name' => 'Colombo',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'andrea.ricci@gmail.com',
                'first_name' => 'Andrea',
                'last_name' => 'Ricci',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'francesca.gallo@yahoo.it',
                'first_name' => 'Francesca',
                'last_name' => 'Gallo',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'simone.marino@libero.it',
                'first_name' => 'Simone',
                'last_name' => 'Marino',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'alice.greco@gmail.com',
                'first_name' => 'Alice',
                'last_name' => 'Greco',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'federico.bruno@outlook.it',
                'first_name' => 'Federico',
                'last_name' => 'Bruno',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'martina.conti@yahoo.it',
                'first_name' => 'Martina',
                'last_name' => 'Conti',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'lorenzo.costantino@gmail.com',
                'first_name' => 'Lorenzo',
                'last_name' => 'Costantino',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'valentina.mancini@libero.it',
                'first_name' => 'Valentina',
                'last_name' => 'Mancini',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'tommaso.giordano@outlook.it',
                'first_name' => 'Tommaso',
                'last_name' => 'Giordano',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'beatrice.rizzo@gmail.com',
                'first_name' => 'Beatrice',
                'last_name' => 'Rizzo',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'matteo.silvestri@yahoo.it',
                'first_name' => 'Matteo',
                'last_name' => 'Silvestri',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'ilaria.moretti@libero.it',
                'first_name' => 'Ilaria',
                'last_name' => 'Moretti',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'riccardo.ferri@gmail.com',
                'first_name' => 'Riccardo',
                'last_name' => 'Ferri',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'amanda.barbieri@outlook.it',
                'first_name' => 'Amanda',
                'last_name' => 'Barbieri',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'nicolo.fontana@yahoo.it',
                'first_name' => 'Nicolò',
                'last_name' => 'Fontana',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'gaia.santoro@gmail.com',
                'first_name' => 'Gaia',
                'last_name' => 'Santoro',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'leonardo.martino@libero.it',
                'first_name' => 'Leonardo',
                'last_name' => 'Martino',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'alice.rinaldi@outlook.it',
                'first_name' => 'Alice',
                'last_name' => 'Rinaldi',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'gabriele.caruso@gmail.com',
                'first_name' => 'Gabriele',
                'last_name' => 'Caruso',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'camilla.villa@yahoo.it',
                'first_name' => 'Camilla',
                'last_name' => 'Villa',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'edoardo.sala@libero.it',
                'first_name' => 'Edoardo',
                'last_name' => 'Sala',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'sofia.pellegrini@gmail.com',
                'first_name' => 'Sofia',
                'last_name' => 'Pellegrini',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'samuele.damico@outlook.it',
                'first_name' => 'Samuele',
                'last_name' => 'D\'Amico',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'aurora.serra@yahoo.it',
                'first_name' => 'Aurora',
                'last_name' => 'Serra',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'riccardo.mariani@gmail.com',
                'first_name' => 'Riccardo',
                'last_name' => 'Mariani',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'vittoria.cattaneo@libero.it',
                'first_name' => 'Vittoria',
                'last_name' => 'Cattaneo',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'dario.battaglia@outlook.it',
                'first_name' => 'Dario',
                'last_name' => 'Battaglia',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'margherita.dangelo@gmail.com',
                'first_name' => 'Margherita',
                'last_name' => 'D\'Angelo',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'federico.marchetti@yahoo.it',
                'first_name' => 'Federico',
                'last_name' => 'Marchetti',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'adriana.sala@libero.it',
                'first_name' => 'Adriana',
                'last_name' => 'Sala',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'daniele.piras@gmail.com',
                'first_name' => 'Daniele',
                'last_name' => 'Piras',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'serena.monti@outlook.it',
                'first_name' => 'Serena',
                'last_name' => 'Monti',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'dario.rubino@yahoo.it',
                'first_name' => 'Dario',
                'last_name' => 'Rubino',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'marta.fabbri@gmail.com',
                'first_name' => 'Marta',
                'last_name' => 'Fabbri',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'vincenzo.capasso@libero.it',
                'first_name' => 'Vincenzo',
                'last_name' => 'Capasso',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'paola.testa@outlook.it',
                'first_name' => 'Paola',
                'last_name' => 'Testa',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'domenico.farina@yahoo.it',
                'first_name' => 'Domenico',
                'last_name' => 'Farina',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'claudia.milani@gmail.com',
                'first_name' => 'Claudia',
                'last_name' => 'Milani',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'stefano.ventura@libero.it',
                'first_name' => 'Stefano',
                'last_name' => 'Ventura',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'silvia.gatti@outlook.it',
                'first_name' => 'Silvia',
                'last_name' => 'Gatti',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'roberto.parisi@yahoo.it',
                'first_name' => 'Roberto',
                'last_name' => 'Parisi',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'elisa.costa@gmail.com',
                'first_name' => 'Elisa',
                'last_name' => 'Costa',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'michele.nicolini@libero.it',
                'first_name' => 'Michele',
                'last_name' => 'Nicolini',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'arianna.montanari@outlook.it',
                'first_name' => 'Arianna',
                'last_name' => 'Montanari',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'alberto.serafini@yahoo.it',
                'first_name' => 'Alberto',
                'last_name' => 'Serafini',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'luciana.farina@gmail.com',
                'first_name' => 'Luciana',
                'last_name' => 'Farina',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'massimo.vincenti@libero.it',
                'first_name' => 'Massimo',
                'last_name' => 'Vincenti',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'caterina.delfino@outlook.it',
                'first_name' => 'Caterina',
                'last_name' => 'Delfino',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'luigi.pugliese@yahoo.it',
                'first_name' => 'Luigi',
                'last_name' => 'Pugliese',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'simona.ferretti@gmail.com',
                'first_name' => 'Simona',
                'last_name' => 'Ferretti',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'angelo.cossu@libero.it',
                'first_name' => 'Angelo',
                'last_name' => 'Cossu',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'silvia.battaglia@outlook.it',
                'first_name' => 'Silvia',
                'last_name' => 'Battaglia',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'gianluca.marras@yahoo.it',
                'first_name' => 'Gianluca',
                'last_name' => 'Marras',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'laura.bottaro@gmail.com',
                'first_name' => 'Laura',
                'last_name' => 'Bottaro',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'emanuele.solinas@libero.it',
                'first_name' => 'Emanuele',
                'last_name' => 'Solinas',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'roberta.pinna@outlook.it',
                'first_name' => 'Roberta',
                'last_name' => 'Pinna',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'piero.salis@yahoo.it',
                'first_name' => 'Piero',
                'last_name' => 'Salis',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'anna.mereu@gmail.com',
                'first_name' => 'Anna',
                'last_name' => 'Mereu',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'alberto.cadeddu@libero.it',
                'first_name' => 'Alberto',
                'last_name' => 'Cadeddu',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'franca.desogus@outlook.it',
                'first_name' => 'Franca',
                'last_name' => 'De Sogus',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'giorgio.lai@yahoo.it',
                'first_name' => 'Giorgio',
                'last_name' => 'Lai',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'paolo.ongini@gmail.com',
                'first_name' => 'Paolo',
                'last_name' => 'Ongini',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'anna.montis@libero.it',
                'first_name' => 'Anna',
                'last_name' => 'Montis',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'stefano.usai@outlook.it',
                'first_name' => 'Stefano',
                'last_name' => 'Usai',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'giovanna.pintus@yahoo.it',
                'first_name' => 'Giovanna',
                'last_name' => 'Pintus',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'michele.virgilio@gmail.com',
                'first_name' => 'Michele',
                'last_name' => 'Virgilio',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'silvia.scano@libero.it',
                'first_name' => 'Silvia',
                'last_name' => 'Scano',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'gianni.fadda@outlook.it',
                'first_name' => 'Gianni',
                'last_name' => 'Fadda',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'valeria.manca@yahoo.it',
                'first_name' => 'Valeria',
                'last_name' => 'Manca',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'massimiliano.boi@gmail.com',
                'first_name' => 'Massimiliano',
                'last_name' => 'Boi',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'donna.saba@libero.it',
                'first_name' => 'Donna',
                'last_name' => 'Saba',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'giacomo.martis@outlook.it',
                'first_name' => 'Giacomo',
                'last_name' => 'Martis',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'cristina.manca@yahoo.it',
                'first_name' => 'Cristina',
                'last_name' => 'Manca',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'efisio.diana@gmail.com',
                'first_name' => 'Efisio',
                'last_name' => 'Diana',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'concetta.pisu@libero.it',
                'first_name' => 'Concetta',
                'last_name' => 'Pisu',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'salvatore.marta@outlook.it',
                'first_name' => 'Salvatore',
                'last_name' => 'Marta',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'angela.carboni@yahoo.it',
                'first_name' => 'Angela',
                'last_name' => 'Carboni',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'gianfranco.milia@gmail.com',
                'first_name' => 'Gianfranco',
                'last_name' => 'Milia',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'antonella.raia@libero.it',
                'first_name' => 'Antonella',
                'last_name' => 'Raia',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'orazio.appera@outlook.it',
                'first_name' => 'Orazio',
                'last_name' => 'Appera',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'serena.sulis@yahoo.it',
                'first_name' => 'Serena',
                'last_name' => 'Sulis',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'antonio.cucca@gmail.com',
                'first_name' => 'Antonio',
                'last_name' => 'Cucca',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'sabrina.morgia@libero.it',
                'first_name' => 'Sabrina',
                'last_name' => 'Morgia',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'domenico.palmas@outlook.it',
                'first_name' => 'Domenico',
                'last_name' => 'Palmas',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'emanuela.lai@yahoo.it',
                'first_name' => 'Emanuela',
                'last_name' => 'Lai',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'giuseppe.sarritzu@gmail.com',
                'first_name' => 'Giuseppe',
                'last_name' => 'Sarritzu',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'caterina.mura@libero.it',
                'first_name' => 'Caterina',
                'last_name' => 'Mura',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'francesco.adedda@outlook.it',
                'first_name' => 'Francesco',
                'last_name' => 'Adedda',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'giuseppina.corgiolu@yahoo.it',
                'first_name' => 'Giuseppina',
                'last_name' => 'Corgiolu',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'vincenzo.sanna@gmail.com',
                'first_name' => 'Vincenzo',
                'last_name' => 'Sanna',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'maria.lecca@libero.it',
                'first_name' => 'Maria',
                'last_name' => 'Lecca',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'roberto.cossu@outlook.it',
                'first_name' => 'Roberto',
                'last_name' => 'Cossu',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'dolores.cucca@yahoo.it',
                'first_name' => 'Dolores',
                'last_name' => 'Cucca',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'marco.serci@gmail.com',
                'first_name' => 'Marco',
                'last_name' => 'Serci',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'giuliana.russo@libero.it',
                'first_name' => 'Giuliana',
                'last_name' => 'Russo',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'stefano.manca@outlook.it',
                'first_name' => 'Stefano',
                'last_name' => 'Manca',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'ilaria.petretto@yahoo.it',
                'first_name' => 'Ilaria',
                'last_name' => 'Petretto',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'pietro.carcangiu@gmail.com',
                'first_name' => 'Pietro',
                'last_name' => 'Carcangiu',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'silvia.obbina@libero.it',
                'first_name' => 'Silvia',
                'last_name' => 'Obbina',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'giovanni.palmas@outlook.it',
                'first_name' => 'Giovanni',
                'last_name' => 'Palmas',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'elena.murgia@yahoo.it',
                'first_name' => 'Elena',
                'last_name' => 'Murgia',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'nicola.cocco@gmail.com',
                'first_name' => 'Nicola',
                'last_name' => 'Cocco',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'patrizia.leoni@libero.it',
                'first_name' => 'Patrizia',
                'last_name' => 'Leoni',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'gianpaolo.pibiri@outlook.it',
                'first_name' => 'Gianpaolo',
                'last_name' => 'Pibiri',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'monica.dettori@yahoo.it',
                'first_name' => 'Monica',
                'last_name' => 'Dettori',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'massimo.puggioni@gmail.com',
                'first_name' => 'Massimo',
                'last_name' => 'Puggioni',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'elisa.carta@libero.it',
                'first_name' => 'Elisa',
                'last_name' => 'Carta',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'gabriele.mereu@outlook.it',
                'first_name' => 'Gabriele',
                'last_name' => 'Mereu',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'chiara.morgia@yahoo.it',
                'first_name' => 'Chiara',
                'last_name' => 'Morgia',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'roberto.cucca@gmail.com',
                'first_name' => 'Roberto',
                'last_name' => 'Cucca',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'caterina.salis@libero.it',
                'first_name' => 'Caterina',
                'last_name' => 'Salis',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'franco.desogus@outlook.it',
                'first_name' => 'Franco',
                'last_name' => 'De Sogus',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'valentina.lai@yahoo.it',
                'first_name' => 'Valentina',
                'last_name' => 'Lai',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'giorgio.ongini@gmail.com',
                'first_name' => 'Giorgio',
                'last_name' => 'Ongini',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'donna.montis@libero.it',
                'first_name' => 'Donna',
                'last_name' => 'Montis',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'sergio.usai@outlook.it',
                'first_name' => 'Sergio',
                'last_name' => 'Usai',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'anna.pintus@yahoo.it',
                'first_name' => 'Anna',
                'last_name' => 'Pintus',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'mirco.virgilio@gmail.com',
                'first_name' => 'Mirco',
                'last_name' => 'Virgilio',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'caterina.scano@libero.it',
                'first_name' => 'Caterina',
                'last_name' => 'Scano',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'gianmatteo.fadda@outlook.it',
                'first_name' => 'Gianmatteo',
                'last_name' => 'Fadda',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'ilaria.manca@yahoo.it',
                'first_name' => 'Ilaria',
                'last_name' => 'Manca',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'efisio.boi@gmail.com',
                'first_name' => 'Efisio',
                'last_name' => 'Boi',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'maria.saba@libero.it',
                'first_name' => 'Maria',
                'last_name' => 'Saba',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'roberto.martis@outlook.it',
                'first_name' => 'Roberto',
                'last_name' => 'Martis',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'giovanna.manca@yahoo.it',
                'first_name' => 'Giovanna',
                'last_name' => 'Manca',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'demo1@demo.com',
                'first_name' => 'Demo',
                'last_name' => 'One',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'demo2@demo.com',
                'first_name' => 'Demo',
                'last_name' => 'Two',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'demo3@demo.com',
                'first_name' => 'Demo',
                'last_name' => 'Three',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'demo4@demo.com',
                'first_name' => 'Demo',
                'last_name' => 'Four',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'demo5@demo.com',
                'first_name' => 'Demo',
                'last_name' => 'Five',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'demo6@demo.com',
                'first_name' => 'Demo',
                'last_name' => 'Six',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'demo7@demo.com',
                'first_name' => 'Demo',
                'last_name' => 'Seven',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'demo8@demo.com',
                'first_name' => 'Demo',
                'last_name' => 'Eight',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'demo9@demo.com',
                'first_name' => 'Demo',
                'last_name' => 'Nine',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'demo10@demo.com',
                'first_name' => 'Demo',
                'last_name' => 'Ten',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'operator1@demo.com',
                'first_name' => 'Operator',
                'last_name' => 'One',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'operator2@demo.com',
                'first_name' => 'Operator',
                'last_name' => 'Two',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'operator3@demo.com',
                'first_name' => 'Operator',
                'last_name' => 'Three',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'operator4@demo.com',
                'first_name' => 'Operator',
                'last_name' => 'Four',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'operator5@demo.com',
                'first_name' => 'Operator',
                'last_name' => 'Five',
                'type' => 'customer_user',
                'password' => 'password',
            ],
            [
                'email' => 'admin@demo.com',
                'first_name' => 'Admin',
                'last_name' => 'User',
                'type' => 'master_admin',
                'password' => 'password',
            ],
        ];
    }
}
